Radius_Of_Sun = int(input("Enter the radius of the Sun (miles) -> "))
print(Radius_Of_Sun)
Radius_Of_Moon = int(input("Enter the radius of the Moon (miles) -> "))
print(Radius_Of_Moon)
Distance_Sun_To_Earth = int(input("Enter the maximum distance to the Sun (miles) -> "))
print(Distance_Sun_To_Earth)
Distance_Moon_To_Earth = int(input("Enter the minimum distance to the Moon (miles) -> "))
print(Distance_Moon_To_Earth)
Rate_of_Moon = float(input("Enter the rate the Moon is moving away (in/year) -> "))
print(Rate_of_Moon)
Exact_Distance_Moon_To_Earth =Distance_Sun_To_Earth*(Radius_Of_Moon / Radius_Of_Sun)
Distance_Recede = Exact_Distance_Moon_To_Earth - Distance_Moon_To_Earth
Time_To_Reach = 12*5280*Distance_Recede/Rate_of_Moon
Time_To_Reach = round(Time_To_Reach)
Distance_Recede='%.2f'%(Distance_Recede)
Exact_Distance_Moon_To_Earth='%.2f'%(Exact_Distance_Moon_To_Earth)
print("The Moon will have exactly the same apparent size as the Sun when it is",Exact_Distance_Moon_To_Earth,"miles away.")
print("The Moon will need to recede another", Distance_Recede, "miles")
print("Which will occur in",Time_To_Reach,"years at the current rate.")